using System.Collections;
using System.Collections.Generic;
using System.Resources;
// using UnityEditor;
// using UnityEditor.Animations;
// using UnityEditor.AssetImporters;
// using UnityEditor.Build.Content;
// using UnityEditor.Build.Reporting;
// using UnityEditor.Presets;
// using UnityEditor.U2D;
// using UnityEditorInternal;
using UnityEngine;
using UnityEngine.AI;
using UnityEngine.Animations;
using UnityEngine.Audio;
using UnityEngine.Experimental.Rendering;
using UnityEngine.Playables;
using UnityEngine.PlayerLoop;
using UnityEngine.Rendering;
using UnityEngine.Tilemaps;
using UnityEngine.U2D;
using UnityEngine.VFX;
using UnityEngine.Video;
// using AnimatorController = UnityEditor.Animations.AnimatorController;
// using BlendTree = UnityEditor.Animations.BlendTree;

public class StaticMono
{
    public static Object Object;
    public static GameObject GameObject;
    public static Component Component;
    // public static LevelGameManager LevelGameManager;
    public static Transform Transform;
    // public static TimeManager TimeManager;
    // public static GlobalGameManager GlobalGameManager;
    public static Behaviour Behaviour;
    // public static GameManager GameManager;
    // public static AudioManager AudioManager;
    // public static InputManager InputManager;
    // public static EditorExtension EditorExtension;
    // public static Physics2DSettings Physics2DSettings;
    public static Camera Camera;
    public static Material Material;
    public static MeshRenderer MeshRenderer;
    public static Renderer Renderer;
    public static Texture Texture;
    public static Texture2D Texture2D;
    // public static OcclusionCullingSettings OcclusionCullingSettings;
    public static GraphicsSettings GraphicsSettings;
    public static MeshFilter MeshFilter;
    public static OcclusionPortal OcclusionPortal;
    public static Mesh Mesh;
    public static Skybox Skybox;
    public static QualitySettings QualitySettings;
    public static Shader Shader;
    public static TextAsset TextAsset;
    public static Rigidbody2D Rigidbody2D;
    public static Collider2D Collider2D;
    public static Rigidbody Rigidbody;
    // public static PhysicsManager PhysicsManager;
    public static Collider Collider;
    public static Joint Joint;
    public static CircleCollider2D CircleCollider2D;
    public static HingeJoint HingeJoint;
    public static PolygonCollider2D PolygonCollider2D;
    public static BoxCollider2D BoxCollider2D;
    public static PhysicsMaterial2D PhysicsMaterial2D;
    public static MeshCollider MeshCollider;
    public static BoxCollider BoxCollider;
    public static CompositeCollider2D CompositeCollider2D;
    public static EdgeCollider2D EdgeCollider2D;
    public static CapsuleCollider2D CapsuleCollider2D;
    public static ComputeShader ComputeShader;
    public static AnimationClip AnimationClip;
    public static ConstantForce ConstantForce;
    // public static TagManager TagManager;
    public static AudioListener AudioListener;
    public static AudioSource AudioSource;
    public static AudioClip AudioClip;
    public static RenderTexture RenderTexture;
    public static CustomRenderTexture CustomRenderTexture;
    public static Cubemap Cubemap;
    public static Avatar Avatar;
    // public static AnimatorController AnimatorController;
    public static RuntimeAnimatorController RuntimeAnimatorController;
    // public static ShaderNameRegistry ShaderNameRegistry;
    public static Animator Animator;
    public static TrailRenderer TrailRenderer;
    // public static DelayedCallManager DelayedCallManager;
    public static TextMesh TextMesh;
    public static RenderSettings RenderSettings;
    public static Light Light;
    // public static ShaderInclude ShaderInclude;
    // public static BaseAnimationTrack BaseAnimationTrack;
    public static Animation Animation;
    public static MonoBehaviour MonoBehaviour;
    // public static MonoScript MonoScript;
    // public static MonoManager MonoManager;
    public static Texture3D Texture3D;
    // public static NewAnimationTrack NewAnimationTrack;
    public static Projector Projector;
    public static LineRenderer LineRenderer;
    public static Flare Flare;
    // public static Halo Halo;
    public static LensFlare LensFlare;
    public static FlareLayer FlareLayer;
    // public static NavMeshProjectSettings NavMeshProjectSettings;
    public static Font Font;
    // public static PlayerSettings PlayerSettings;
    // public static NamedObject NamedObject;
    public static PhysicMaterial PhysicMaterial;
    public static SphereCollider SphereCollider;
    public static CapsuleCollider CapsuleCollider;
    public static SkinnedMeshRenderer SkinnedMeshRenderer;
    public static FixedJoint FixedJoint;
    // public static BuildSettings BuildSettings;
    public static AssetBundle AssetBundle;
    public static CharacterController CharacterController;
    public static CharacterJoint CharacterJoint;
    public static SpringJoint SpringJoint;
    public static WheelCollider WheelCollider;
    public static ResourceManager ResourceManager;
    // public static PreloadData PreloadData;
    // public static MovieTexture MovieTexture;
    public static ConfigurableJoint ConfigurableJoint;
    public static TerrainCollider TerrainCollider;
    public static TerrainData TerrainData;
    public static LightmapSettings LightmapSettings;
    public static WebCamTexture WebCamTexture;
    // public static EditorSettings EditorSettings;
    // public static EditorUserSettings EditorUserSettings;
    public static AudioReverbFilter AudioReverbFilter;
    public static AudioHighPassFilter AudioHighPassFilter;
    public static AudioChorusFilter AudioChorusFilter;
    public static AudioReverbZone AudioReverbZone;
    public static AudioEchoFilter AudioEchoFilter;
    public static AudioLowPassFilter AudioLowPassFilter;
    public static AudioDistortionFilter AudioDistortionFilter;
    public static SparseTexture SparseTexture;
    public static AudioBehaviour AudioBehaviour;
    // public static AudioFilter AudioFilter;
    public static WindZone WindZone;
    public static Cloth Cloth;
    // public static SubstanceArchive SubstanceArchive;
    // public static ProceduralMaterial ProceduralMaterial;
    // public static ProceduralTexture ProceduralTexture;
    public static Texture2DArray Texture2DArray;
    public static CubemapArray CubemapArray;
    public static OffMeshLink OffMeshLink;
    public static OcclusionArea OcclusionArea;
    public static Tree Tree;
    public static NavMeshAgent NavMeshAgent;
    // public static NavMeshSettings NavMeshSettings;
    public static ParticleSystem ParticleSystem;
    public static ParticleSystemRenderer ParticleSystemRenderer;
    public static ShaderVariantCollection ShaderVariantCollection;
    public static LODGroup LODGroup;
    // public static BlendTree BlendTree;
    public static Motion Motion;
    public static NavMeshObstacle NavMeshObstacle;
    public static SortingGroup SortingGroup;
    public static SpriteRenderer SpriteRenderer;
    public static Sprite Sprite;
    // public static CachedSpriteAtlas CachedSpriteAtlas;
    public static ReflectionProbe ReflectionProbe;
    public static Terrain Terrain;
    public static LightProbeGroup LightProbeGroup;
    public static AnimatorOverrideController AnimatorOverrideController;
    public static CanvasRenderer CanvasRenderer;
    public static Canvas Canvas;
    public static RectTransform RectTransform;
    public static CanvasGroup CanvasGroup;
    public static BillboardAsset BillboardAsset;
    public static BillboardRenderer BillboardRenderer;
    // public static SpeedTreeWindAsset SpeedTreeWindAsset;
    public static AnchoredJoint2D AnchoredJoint2D;
    public static Joint2D Joint2D;
    public static SpringJoint2D SpringJoint2D;
    public static DistanceJoint2D DistanceJoint2D;
    public static HingeJoint2D HingeJoint2D;
    public static SliderJoint2D SliderJoint2D;
    public static WheelJoint2D WheelJoint2D;
    // public static ClusterInputManager ClusterInputManager;
    // public static BaseVideoTexture BaseVideoTexture;
    public static NavMeshData NavMeshData;
    public static AudioMixer AudioMixer;
    // public static AudioMixerController AudioMixerController;
    // public static AudioMixerGroupController AudioMixerGroupController;
    // public static AudioMixerEffectController AudioMixerEffectController;
    // public static AudioMixerSnapshotController AudioMixerSnapshotController;
    public static PhysicsUpdateBehaviour2D PhysicsUpdateBehaviour2D;
    public static ConstantForce2D ConstantForce2D;
    public static Effector2D Effector2D;
    public static AreaEffector2D AreaEffector2D;
    public static PointEffector2D PointEffector2D;
    public static PlatformEffector2D PlatformEffector2D;
    public static SurfaceEffector2D SurfaceEffector2D;
    public static BuoyancyEffector2D BuoyancyEffector2D;
    public static RelativeJoint2D RelativeJoint2D;
    public static FixedJoint2D FixedJoint2D;
    public static FrictionJoint2D FrictionJoint2D;
    public static TargetJoint2D TargetJoint2D;
    public static LightProbes LightProbes;
    public static LightProbeProxyVolume LightProbeProxyVolume;
    // public static SampleClip SampleClip;
    public static AudioMixerSnapshot AudioMixerSnapshot;
    public static AudioMixerGroup AudioMixerGroup;
    public static AssetBundleManifest AssetBundleManifest;
    // public static RuntimeInitializeOnLoadManager RuntimeInitializeOnLoadManager;
    // public static UnityConnectSettings UnityConnectSettings;
    public static AvatarMask AvatarMask;
    public static PlayableDirector PlayableDirector;
    public static VideoPlayer VideoPlayer;
    public static VideoClip VideoClip;
    public static ParticleSystemForceField ParticleSystemForceField;
    public static SpriteMask SpriteMask;
    // public static OcclusionCullingData OcclusionCullingData;
    // public static PrefabInstance PrefabInstance;
    // public static EditorExtensionImpl EditorExtensionImpl;
    // public static AssetImporter AssetImporter;
    // public static Mesh3DSImporter Mesh3DSImporter;
    // public static TextureImporter TextureImporter;
    // public static ShaderImporter ShaderImporter;
    // public static ComputeShaderImporter ComputeShaderImporter;
    // public static AudioImporter AudioImporter;
    // public static HierarchyState HierarchyState;
    // public static AssetMetaData AssetMetaData;
    // public static DefaultAsset DefaultAsset;
    // public static DefaultImporter DefaultImporter;
    // public static TextScriptImporter TextScriptImporter;
    // public static SceneAsset SceneAsset;
    // public static NativeFormatImporter NativeFormatImporter;
    // public static MonoImporter MonoImporter;
    // public static LibraryAssetImporter LibraryAssetImporter;
    // public static ModelImporter ModelImporter;
    // public static FBXImporter FBXImporter;
    // public static TrueTypeFontImporter TrueTypeFontImporter;
    // public static EditorBuildSettings EditorBuildSettings;
    // public static InspectorExpandedState InspectorExpandedState;
    // public static AnnotationManager AnnotationManager;
    // public static PluginImporter PluginImporter;
    // public static EditorUserBuildSettings EditorUserBuildSettings;
    // public static IHVImageFormatImporter IHVImageFormatImporter;
    // public static AnimatorStateTransition AnimatorStateTransition;
    // public static AnimatorState AnimatorState;
    // public static HumanTemplate HumanTemplate;
    // public static AnimatorStateMachine AnimatorStateMachine;
    // public static PreviewAnimationClip PreviewAnimationClip;
    // public static AnimatorTransition AnimatorTransition;
    // public static SpeedTreeImporter SpeedTreeImporter;
    // public static AnimatorTransitionBase AnimatorTransitionBase;
    // public static SubstanceImporter SubstanceImporter;
    // public static LightmapParameters LightmapParameters;
    // public static LightingDataAsset LightingDataAsset;
    // public static SketchUpImporter SketchUpImporter;
    // public static BuildReport BuildReport;
    // public static PackedAssets PackedAssets;
    // public static VideoClipImporter VideoClipImporter;
    public static int int1;
    public static bool bool1;
    public static float float1;
    // public static MonoObject MonoObject;
    public static Collision Collision;
    // public static Vector3f Vector3f;
    // public static RootMotionData RootMotionData;
    public static Collision2D Collision2D;
    // public static AudioMixerLiveUpdateFloat AudioMixerLiveUpdateFloat;
    // public static AudioMixerLiveUpdateBool AudioMixerLiveUpdateBool;
    // public static Polygon2D Polygon2D;
    public static TilemapCollider2D TilemapCollider2D;
    // public static AssetImporterLog AssetImporterLog;
    // public static VFXRenderer VFXRenderer;
    public static Grid Grid;
    // public static ScenesUsingAssets ScenesUsingAssets;
    public static ArticulationBody ArticulationBody;
    // public static Preset Preset;
    public static IConstraint IConstraint;
    // public static AssemblyDefinitionReferenceImporter AssemblyDefinitionReferenceImp;
    // public static AssetImportInProgressProxy AssetImportInProgressProxy;
    // public static PluginBuildInfo PluginBuildInfo;
    // public static MemorySettings MemorySettings;
    // public static EditorProjectAccess EditorProjectAccess;
    // public static PrefabImporter PrefabImporter;
    public static TilemapRenderer TilemapRenderer;
    // public static SpriteAtlasAsset SpriteAtlasAsset;
    // public static SpriteAtlasDatabase SpriteAtlasDatabase;
    // public static AudioBuildInfo AudioBuildInfo;
    // public static CachedSpriteAtlasRuntimeData CachedSpriteAtlasRuntimeData;
    // public static AssemblyDefinitionReferenceAsset AssemblyDefinitionReferenceAss;
    // public static BuiltAssetBundleInfoSet BuiltAssetBundleInfoSet;
    public static SpriteAtlas SpriteAtlas;
    // public static RayTracingShaderImporter RayTracingShaderImporter;
    // public static PreviewImporter PreviewImporter;
    public static RayTracingShader RayTracingShader;
    public static LightingSettings LightingSettings;
    // public static PlatformModuleSetup PlatformModuleSetup;
    // public static VersionControlSettings VersionControlSettings;
    public static CustomCollider2D CustomCollider2D;
    public static AimConstraint AimConstraint;
    // public static VFXManager VFXManager;
    // public static RuleSetFileAsset RuleSetFileAsset;
    // public static VisualEffectSubgraph VisualEffectSubgraph;
    // public static VisualEffectSubgraphOperator VisualEffectSubgraphOperator;
    // public static VisualEffectSubgraphBlock VisualEffectSubgraphBlock;
    // public static Prefab Prefab;
    // public static LocalizationImporter LocalizationImporter;
    // public static ReferencesArtifactGenerator ReferencesArtifactGenerator;
    // public static AssemblyDefinitionAsset AssemblyDefinitionAsset;
    // public static SceneVisibilityState SceneVisibilityState;
    public static LookAtConstraint LookAtConstraint;
    // public static SpriteAtlasImporter SpriteAtlasImporter;
    // public static MultiArtifactTestImporter MultiArtifactTestImporter;
    // public static GameObjectRecorder GameObjectRecorder;
    // public static LightingDataAssetParent LightingDataAssetParent;
    // public static PresetManager PresetManager;
    // public static StreamingManager StreamingManager;
    // public static LowerResBlitTexture LowerResBlitTexture;
    // public static VideoBuildInfo VideoBuildInfo;
    public static StreamingController StreamingController;
    // public static AndroidAssetPackImporter AndroidAssetPackImporter;
    public static GridLayout GridLayout;
    // public static AssemblyDefinitionImporter AssemblyDefinitionImporter;
    public static ParentConstraint ParentConstraint;
    // public static RuleSetFileImporter RuleSetFileImporter;
    public static PositionConstraint PositionConstraint;
    public static RotationConstraint RotationConstraint;
    public static ScaleConstraint ScaleConstraint;
    public static Tilemap Tilemap;
    // public static PackageManifest PackageManifest;
    // public static PackageManifestImporter PackageManifestImporter;
    public static TerrainLayer TerrainLayer;
    public static SpriteShapeRenderer SpriteShapeRenderer;
    public static VisualEffectAsset VisualEffectAsset;
    // public static VisualEffectImporter VisualEffectImporter;
    // public static VisualEffectResource VisualEffectResource;
    public static VisualEffectObject VisualEffectObject;
    public static VisualEffect VisualEffect;
    public static LocalizationAsset LocalizationAsset;
    // public static UnityEditor.AssetImporters.ScriptedImporter ScriptedImporter;
    // public static ShaderIncludeImporter ShaderIncludeImporter;
}